# Generated by Django 5.2.17 on 2026-09-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('imagen', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['fecha', 'nombre'],
            },
        ),
    ]
