# Generated by Django 5.2.17 on 2026-09-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_importar_eventos_iniciales'),
        ('usuarios', '0003_perfilpostulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'categoría de oferta',
                'verbose_name_plural': 'categorías de ofertas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('hibrida', 'Híbrida'), ('remota', 'Remota')], default='presencial', max_length=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='eventos.categoriaoferta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='eventos.empresa')),
            ],
            options={
                'ordering': ['-fecha_publicacion', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('revision', 'En revisión'), ('entrevista', 'Entrevista'), ('seleccionada', 'Seleccionada'), ('rechazada', 'Rechazada')], default='recibida', max_length=12)),
                ('carta_presentacion', models.TextField(blank=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='eventos.ofertalaboral')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.perfilpostulante')),
            ],
            options={
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='ofertalaboral',
            constraint=models.CheckConstraint(condition=models.Q(('salario_minimo__isnull', True), ('salario_maximo__isnull', True), ('salario_maximo__gte', models.F('salario_minimo')), _connector='OR'), name='oferta_rango_salario_valido'),
        ),
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(fields=('oferta', 'postulante'), name='postulacion_unica_por_oferta_y_usuario'),
        ),
    ]
