# Generated by Django 5.2.17 on 2026-09-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(default='invitado', max_length=50)),
            ],
            options={
                'verbose_name': 'usuario del sitio',
                'verbose_name_plural': 'usuarios del sitio',
                'ordering': ['usuario'],
            },
        ),
    ]
