# Generated by Django 5.2.17 on 2026-09-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_importar_usuarios_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('profesion', models.CharField(blank=True, max_length=150)),
                ('resumen_profesional', models.TextField(blank=True)),
                ('habilidades', models.TextField(blank=True, help_text='Separar habilidades con comas.')),
                ('curriculum_url', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_postulante', to='usuarios.usuariositio')),
            ],
            options={
                'verbose_name': 'perfil postulante',
                'verbose_name_plural': 'perfiles postulantes',
                'ordering': ['usuario__nombre'],
            },
        ),
    ]
